# REST API Server on Live Firebase
@baseUrl = https://us-central1-shinwei-alphaschedult.cloudfunctions.net/api

###  Create a new event
POST {{baseUrl}}/event/create/mq4U96Grkdrtq2mF6k5X
Content-Type: application/json

{
    "eventName": "Event1",
    "calendar": "2021-02-06",
    "startTime": "01:57 PM",
    "endTime": "02:00 PM",
    "description": "This is a description",
    "calendarId": "mq4U96Grkdrtq2mF6k5X"
}

### Get event by id
GET {{baseUrl}}/event/get/ixSn5CtwFc1ZqLOlkL2c

### Get event list from the calendar
GET {{baseUrl}}/event/getList/Hf9ucu5ztrKfDp3NtbZ5

### Update event
PATCH {{baseUrl}}/event/update/ixSn5CtwFc1ZqLOlkL2c
Content-Type: application/json

{
    "eventName": "Event12345",
    "description": "Hello world"
}

### Delete event
DELETE {{baseUrl}}/event/delete/OMW15qlpkVUhqgwdhm5t
