# REST API Server on Live Firebase
@baseUrl = https://us-central1-alpha-schedule-bae8b.cloudfunctions.net/api
###  Create a new event
POST {{baseUrl}}/event/create/8SBoGl3RYFyJVZhj1npp
Content-Type: application/json

{
    "eventName": "Event3",
    "calendar": "DateTime(2021, 1, 30)",
    "startTime": "TimeOfDay(hour: 9, minute: 36)",
    "endTime": "TimeOfDay(hour: 16, minute: 44)",
    "description": "This is a description",
    "calendarId": "npp"
}

### Get event by id
GET {{baseUrl}}/event/get/ixSn5CtwFc1ZqLOlkL2c

### Get event list from the calendar
GET {{baseUrl}}/event/getList/fdBXfvtaBvCNEpUFMB72

### Update event
PATCH {{baseUrl}}/event/update/ixSn5CtwFc1ZqLOlkL2c
Content-Type: application/json

{
    "eventName": "Event12345",
    "description": "Hello world"
}

### Delete event
DELETE {{baseUrl}}/event/delete/rkippIBVBLjgu9IDKXMO
