//@baseUrl = http://localhost:5001/alpha-schedule-bae8b/us-central1/api
//@baseUrl = https://us-central1-alpha-schedule-bae8b.cloudfunctions.net/api
//@baseUrl = http://localhost:5001/wk-backend-firebase-alpha/us-central1/api
@baseUrl = https://us-central1-wk-backend-firebase-alpha.cloudfunctions.net/api
### Create a new calendar
POST {{baseUrl}}/calendar/create/S4JVOF9LGTYmkTpxsliA
Content-Type: application/json

{
    "calendarName": "Calendar Name",
    "description" : "This is a calendar",
    "color" : "Colors.blue[50]",
    "eventList": [],
    "accessibility": "View Only",
    "owner": "",
    "members": []
}

### Get calendar by id
GET {{baseUrl}}/calendar/get/9gxEEO1kZYlFQOyxsur0

### Get calendar list by userid
GET {{baseUrl}}/calendar/getList/qjoFiAZkIXKa2aYCAJNO

### Delete the calendar
DELETE {{baseUrl}}/calendar/delete/PUFQmJ6uiASYrySOvhrh

### Create a new user
POST {{baseUrl}}/user/create
Content-Type: application/json

{
    "name": "Tok Kai Xian",
    "email" : "kaixianp@gmail.com",
    "phone" : "01113005114",
    "gender": "Male",
    "password": "123",
    "calendarList": [""],
    "collaboratorCalendarList": []
}

### Get user list
GET {{baseUrl}}/user

### Create a new event
POST {{baseUrl}}/event/create
Content-Type: application/json

{
    "eventName": "Event Name",
    "calendar" : "DateTime(2021, 1, 12)",
    "startTime" : "TimeOfDay(hour: 9, minute: 36)",
    "endTime": "TimeOfDay(hour: 16, minute: 44)",
    "description": "This is a description"
}

### Get a User list
GET {{baseUrl}}/user/

### Get a User by Id
GET {{baseUrl}}/user/jtCjtuOowozN64OyGgXV

### Update the user
PATCH {{baseUrl}}/user/D2mAeYekIv0JNPtepX65
Content-Type: application/json

{
    "name": "Tan Wei Kok",
    "email": "wktan@graduate.utm.my"
}

### Delete the user
DELETE {{baseUrl}}/user/delete/jtCjtuOowozN64OyGgXV
