@baseUrl = https://us-central1-shinwei-alphaschedult.cloudfunctions.net/api

### Create a new calendar with user id
POST {{baseUrl}}/calendar/gqF7Us5x4NsqbALpvhAA
Content-Type: application/json

{
    "calendarName": "Calendar2",
    "description" : "This is a calendar",
    "color" : "Colors.blue[50]",
    "eventList": [],
    "accessibility": "View Only",
    "ownersId": "",
    "membersId": []
}

### Get calendar by id
GET {{baseUrl}}/calendar/v0AUriLx5oqmqYoI04li

### Get calendar list by userid
GET {{baseUrl}}/calendar/getCalendarList/eHAyvyAtI1pygJXOcQpU

### Get collaborator calendar list by userid
GET {{baseUrl}}/calendar/getCollaboratorCalendarList/1SZirlKOZmumW07Z29h8

### Delete the calendar
DELETE {{baseUrl}}/calendar/FVUmRl70gYbFsSPCMmgc

### Get calendar members by calendar id
GET {{baseUrl}}/calendar/getCalendarMembers/SqTYznbGvnkKFPXlfTME

### Create a new user
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "tzq",
    "email" : "kaixianp@gmail.com",
    "phone" : "01113005114",
    "gender": "Male",
    "password": "12345678",
    "calendarList": [],
    "collaboratorCalendarList": []
}

### Get user list
GET {{baseUrl}}/user

### Create a new event
POST {{baseUrl}}/event
Content-Type: application/json

{
    "eventName": "Event Name",
    "calendar" : "DateTime(2021, 1, 12)",
    "startTime" : "TimeOfDay(hour: 9, minute: 36)",
    "endTime": "TimeOfDay(hour: 16, minute: 44)",
    "description": "This is a description"
}

### Get a User list
GET {{baseUrl}}/user/

### Get a User by Id
GET {{baseUrl}}/user/eHAyvyAtI1pygJXOcQpU


### Update the user
PATCH {{baseUrl}}/user/D2mAeYekIv0JNPtepX65
Content-Type: application/json

{
    "name": "Tan Wei Kok",
    "email": "wktan@graduate.utm.my"
}

### Delete the user
DELETE {{baseUrl}}/user/delete/jtCjtuOowozN64OyGgXV
