@baseUrl = http://localhost:5001/alpha-schedule-bae8b/us-central1/api

### Create a new calendar with user id
POST {{baseUrl}}/calendar/eNXlTphqgVT0TmKA5MC4
Content-Type: application/json

{
    "accessibility": "Editable",
    "calendarName": "c1",
    "color": "Light Blue",
    "description": "des",
    "eventList":[],
    "id": null,
    "membersId": [],
    "ownerId": null
}

### Get calendar by id
GET {{baseUrl}}/calendar/v0AUriLx5oqmqYoI04li

### Get calendar list by userid
GET {{baseUrl}}/calendar/getCalendarList/7lJMgJy0yBlNsxy4BiIy

### Get collaborator calendar list by userid
GET {{baseUrl}}/calendar/getCollaboratorCalendarList/1SZirlKOZmumW07Z29h8

### Delete the calendar
DELETE {{baseUrl}}/calendar/FVUmRl70gYbFsSPCMmgc

### Get calendar members by calendar id
GET {{baseUrl}}/calendar/getCalendarMembers/SqTYznbGvnkKFPXlfTME

### Create a new user
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "csw",
    "email" : "csw@gmail.com",
    "phone" : "01113005114",
    "gender": "Male",
    "password": "12345678",
    "calendarList": [],
    "collaboratorCalendarList": []
}

### Get user list
GET {{baseUrl}}/user

### Get a User list
GET {{baseUrl}}/user/

### Get a User by Id
GET {{baseUrl}}/user/eHAyvyAtI1pygJXOcQpU

### Update the user
PATCH {{baseUrl}}/user/D2mAeYekIv0JNPtepX65
Content-Type: application/json

{
    "name": "Tan Wei Kok",
    "email": "wktan@graduate.utm.my"
}

### Delete the user
DELETE {{baseUrl}}/user/delete/jtCjtuOowozN64OyGgXV

### Add collaborator to the calendar
PATCH {{baseUrl}}/calendar/add/1qR1LKkv7QPFJur0a5re/HRY8BzxjRlYLloTtTyja